### ISSUE TITLE
Create a hex sticker

### ISSUE THREAD

**Issue by lewinfox** [lewinfox/levitate#6]
For eye candy...

**Comment by zatch3301** [comment]
Can I work on this?

**Comment by lewinfox** [comment]
@zatch3301 Please do! Thank you 😄

**Comment by zatch3301** [comment]
please check #8 #9  let me know if you need any changes.

**Comment by zatch3301** [comment]
![hex-levitate](https://user-images.githubusercontent.com/46402550/126183655-8882a94a-7d5c-4de6-9fc3-982b6fb89cab.png)

**Comment by lewinfox** [comment]
Closed by #8
